---
title: "Notes for Final Report"
subtitle: "EDE Fall 2024"
author: "Emily Yang"
date: "2024-10-22"
output: pdf_document
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Shortcuts
Create code chunk: Ctrl+Alt+I


## R Markdown
(Also refer to Markdown cheat sheet)

- Include toc (table of content) and subtitle at the beginning of the report
- toc for figures: \ + listoffigures
- inset a new page: \ + newpage
- insert tables, images, links, format bullet points
  * Help > Markdown Quick Reference
  * [my link] (http://rmarkdown.rstudio.com)

### r code chunk settings
- Echo = F: only show the output
- include = F: run the code but do not show the code
- eval = F, include = F: never run and show up in output
- fig.height = 3, fig.width = 5: set absolute size of figure
- fig.dim: set both (e.g. fig.dim = c(5,3))
- fig.cap = "Figure 1": Figure caption (if want a different caption for each figure, then need multiple individual code chunks)
- out.width.out.height: scale figs in output docs (e.g. out.width = 80% is setting at 80% of page width)
- fig.align: set alignment('left', 'center', etc.)


## Other
